### ISSUE TITLE
0.2.0 goals sorta

### ISSUE THREAD

**Issue by Halatnikov** [Halatnikov/linum-framework#1]
## high priority:
- [ ]  clean up ***all*** the code after 0.1.0 and fix bugs in the process

- [ ]  ***hopefully*** also fix gameplay bugs (i might need help on this)

- [ ]  add a few more essential objects and special objects

## lower priority:

- [ ]  skin system (make it work in multiplayer too)

- [ ]  better menus (at least main menu and level/skin select for now)

- [ ]  beta update branch

- [ ]  some kind of "installer" if no resource files are present

## even lower priority (might delay):

- [ ]  level finish

- [ ]  music player

- [ ]  logging

- [ ]  bring back language translation

- [ ]  settings and saving of them (at least just an .ini file without a menu)
